name: bafa
on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: eclipse-paho/paho.mqtt.embedded-c
        ref: master 
    - name: 下载gcc
      uses: lmq8267/dl-musl@main
      with:
        target: mipsel-linux-muslsf
        static: true
        gccpath: /tmp
    - name: 安装 UPX
      uses: crazy-max/ghaction-upx@v3
      with:
        version: latest
        install-only: true
    - name: 编译
      run: |
         mipsel-linux-muslsf-gcc -v
         echo $CFLAGS

         sed -i 's/SHARED/STATIC/g' MQTTPacket/src/CMakeLists.txt
         sed -i 's/SHARED/STATIC/g' MQTTClient-C/src/CMakeLists.txt
         mkdir -p build bin && cd build
         export CC="$CC -static"
         cmake ..
         make
         
         cp -f MQTTClient-C/samples/linux/stdoutsubc bin/
         file bin/stdoutsubc
         $STRIP bin/stdoutsubc
         file bin/stdoutsubc
         upx --lzma --best bin/stdoutsubc
    - uses: actions/upload-artifact@v4
      with:
        name: bafa
        path: bin/stdoutsubc
