name: 打包WEB网页

on:
  workflow_dispatch:
    inputs:
      repo:
        description: '请输入EasyTier源码仓库'
        required: true
        default: 'cn1095/EasyTier'
      branch:
        description: '请输入仓库的分支或版本号，默认main分支'
        required: true
        default: 'main'
      scp:
        description: '上传静态网页文件到服务器'
        required: true
        default: false
        type: boolean
env:
  branch: ${{ github.event.inputs.branch || 'main' }} # 为 branch 设置默认值
  repo: ${{ github.event.inputs.repo || 'cn1095/EasyTier' }} # 为 repo 设置默认值
  CARGO_TERM_COLOR: always
  TZ: Asia/Shanghai

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 克隆源码
        run: git clone -b ${{ env.branch }} https://github.com/${{ env.repo }} /opt/et
      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21' # 使用的 Node.js 版本，可调整
      - name: 安装pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      - name: 构建 HTML
        run: |
          cd /opt/et
          pnpm -r install
          pnpm -r build
      - name: 上传文件
        uses: actions/upload-pages-artifact@v3
        with:
          path: '/opt/et/easytier-web/frontend/dist'
