name: 测试 Key

on:
  workflow_dispatch:

jobs:
  generate-key:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 编译安装 OpenSSL 
        run: |
          wget https://www.openssl.org/source/old/1.0.2/openssl-1.0.2u.tar.gz
          tar xzf openssl-1.0.2u.tar.gz
          cd openssl-1.0.2u
          ./config no-shared --prefix=$HOME/openssl-1.0.2u
          make -j$(nproc)
          make install_sw
          echo "$HOME/openssl-1.0.2u/bin" >> $GITHUB_PATH

      - name: 生成 
        run: |
          openssl version
          openssl ecparam -name prime192v1 -genkey -noout -out prikey.pem
          openssl ec -in prikey.pem -outform DER -out prikey.der
          stat -c %s prikey.der
         
