name: node
on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
       repository: 'nodejs/node'
       
    - name: 下载gcc
      uses: lmq8267/dl-musl@main
      with:
        target: mipsel-linux-muslsf
        static: true
        gccpath: /tmp

    - name: build
      run: |
         ./configure --help || true
         ./configure --dest-cpu=mipsel --cross-compiling --without-node-snapshot --without-ssl --fully-static --partly-static --with-mips-float-abi soft --enable-static
         make
        

    - uses: actions/upload-artifact@v4
      with:
        name: node
        path: bin
