name: php
on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
       repository: cn1095/static-php-cli
    - name: 下载gcc
      uses: lmq8267/dl-musl@main
      with:
        target: mipsel-linux-muslsf
        static: true
        gccpath: /tmp

    - name: build
      run: |
         curl -fsSL -o spc https://dl.static-php.dev/static-php-cli/spc-bin/nightly/spc-linux-x86_64
         chmod +x ./spc
         ./spc --version
         #export CONFIGURE_HOST="mipsel-linux-muslsf"
         #export CFLAGS="$CFLAGS -Wno-error=missing-include-dirs"
         #export CXXFLAGS="$CXXFLAGS -Wno-error=missing-include-dirs"
         #sudo apt update
         #sudo apt install qemu-user qemu-user-static binfmt-support
         #sudo update-binfmts --enable qemu-mipsel
         sudo cp -rf $STRIP $(which strip)
         #export QEMU_BINARY=qemu-mipsel
         #./spc doctor --auto-fix
         ./spc download --with-php=8.2 --for-extensions "apcu,bcmath,calendar,ctype,curl,dba,dom,exif,fileinfo,openssl,filter,gd,iconv,intl,mbregex,mbstring,mysqli,mysqlnd,opcache,pcntl,pdo,pdo_mysql,pdo_pgsql,pdo_sqlite,pgsql,phar,posix,readline,redis,session,simplexml,sockets,sodium,spx,sqlite3,tokenizer,uuid,uv,xml,xmlreader,xmlwriter,xsl,zip,zlib"
         ./spc install-pkg upx
         ./spc build --build-all "apcu,bcmath,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,gd,iconv,intl,openssl,mbregex,mbstring,mysqli,mysqlnd,opcache,pcntl,pdo,pdo_mysql,pdo_pgsql,pdo_sqlite,pgsql,phar,posix,readline,redis,session,simplexml,sockets,sodium,spx,sqlite3,tokenizer,uuid,uv,xml,xmlreader,xmlwriter,xsl,zip,zlib" --with-upx-pack --debug --build-all
    - uses: actions/upload-artifact@v4
      with:
        name: php
        path: /opt/bin
